// Code generated by alef — DO NOT EDIT.
// alef:hash:734d07d784c116e6d1de74a7434fc035ed2de3f5b01b50d6944be2c68641a3d4
package htmltomarkdown

// RequireNativeSetup_3_16_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_16_0 = "3.16.0"
