// Code generated by alef — DO NOT EDIT.
// alef:hash:a68d6bc794eba52f4277d036f2d2d39c11d68c429e87b5c9400424e28ff0c775
package htmltomarkdown

// RequireNativeSetup_3_17_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_17_0 = "3.17.0"
