// Code generated by alef — DO NOT EDIT.
// alef:hash:3991c9081551dfe80c3d465050a26875761ed8043df355c17b6d3266111ea9cb
package htmltomarkdown

// RequireNativeSetup_3_17_1 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_17_1 = "3.17.1"
