# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4df80fbc937ce8a9162531258b47471abfd67ad199b7d98cb08655ebe6db19f2
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.17.1"
end
