# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31cca426bed4cf070e9b4260d3264c73700befe6d2315f631edfc4885e1f3252
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.17.0"
end
