# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9cd1523beb892a6e5eef0c33a956855a8178865245dbf115fe62ed9e618d85ab
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.16.0"
end
