// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ae2acc5fdead0694975c3b4d4a99357e8132f82ec8d81defd6bf3a5dce304d1f
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new HtmlToMarkdownRsException. */
  public HtmlToMarkdownRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new HtmlToMarkdownRsException with the given message. */
  public HtmlToMarkdownRsException(final String message) {
    super(message);
    this.code = -1;
  }

  /** Creates a new HtmlToMarkdownRsException with a cause. */
  public HtmlToMarkdownRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
