// DO NOT EDIT - auto-generated by alef
// alef:hash:6461a96933b317a1a2ae04da64ff14bcb0ef9a28250665c2be80f3c3cd7e6c2a
package io.xberg.htmltomarkdown;

/**
 * Input exceeds the configured byte limit.
 */
public class InputTooLargeException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InputTooLargeException with the given message. */
  public InputTooLargeException(final String message) {
    super(message);
  }

  /** Creates a new InputTooLargeException with the given message and cause. */
  public InputTooLargeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
