// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bf53fb20f903880cb374f10cb5278800f26987f09ec73760f364a79a9bcd3eff
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

final class JsonMapperFactory {
    private JsonMapperFactory() {}

    static com.fasterxml.jackson.databind.ObjectMapper withNativePathSerialization(
            final com.fasterxml.jackson.databind.ObjectMapper mapper) {
        var module = new com.fasterxml.jackson.databind.module.SimpleModule();
        module.addSerializer(
            java.nio.file.Path.class,
            com.fasterxml.jackson.databind.ser.std.ToStringSerializer.instance);
        return mapper.registerModule(module);
    }
}
