# Generated by alef. Do not edit by hand.
# alef:hash:5facef71781c2f633276cc98a0efd30659e139fb5c220e6d4b3e2e55dc0ff49f

defmodule E2eElixir.MixProject do
  use Mix.Project

  def project do
    [
      app: :e2e_elixir,
      version: "0.1.0",
      elixir: "~> 1.14",
      deps: deps()
    ]
  end

  defp deps do
    [
      {:html_to_markdown, path: "../../packages/elixir"},
      {:rustler_precompiled, "~> 0.10"},
      {:rustler, "~> 0.38", runtime: false}
    ]
  end
end
