// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:181ad9dd7aab9a6f186ce2e9e2d16eaddd1c40c10b6520d464e77a059d645ca6
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
  name: "E2eSwift",
  platforms: [
    .macOS(.v13),
    .iOS(.v16),
  ],
  dependencies: [
    .package(url: "https://github.com/xberg-io/html-to-markdown", branch: "release/swift/3.17.1"),
  ],
  targets: [
    .testTarget(
      name: "HtmlToMarkdownE2ETests",
      dependencies: [.product(name: "HtmlToMarkdown", package: "html-to-markdown")]
    ),
  ]
)
