// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:276931ce85d5644ff0cd9030d96d6c8c79565b421130f4eca011fabe593038a7
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
  name: "E2eSwift",
  platforms: [
    .macOS(.v13),
    .iOS(.v16),
  ],
  dependencies: [
    .package(url: "https://github.com/xberg-io/html-to-markdown", branch: "release/swift/3.17.0"),
  ],
  targets: [
    .testTarget(
      name: "HtmlToMarkdownE2ETests",
      dependencies: [.product(name: "HtmlToMarkdown", package: "html-to-markdown")]
    ),
  ]
)
