# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3a66d9697238953f8ba79544e12d060bebe7b568f5b0dd12b6f90ce403a7f406
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true
# Dependency versions here are alef-managed and are rewritten on every `alef build`. ~keep
# To raise one durably, set it in `[crates.ruby.dependency_versions]`; a direct edit to this file is discarded.

Gem::Specification.new do |spec|
  spec.name = "html-to-markdown"
  spec.version = "3.15.1"
  spec.authors       = ["Na'aman Hirschfeld <naaman@xberg.io>"]
  spec.summary       = "High-performance HTML to Markdown converter"
  spec.description   = "High-performance HTML to Markdown converter"
  spec.homepage      = "https://github.com/xberg-io/html-to-markdown"

  spec.license       = "MIT"

  spec.required_ruby_version = ">= 3.2.0"
  spec.metadata["keywords"] = %w[converter html markdown].join(",")
  spec.metadata["rubygems_mfa_required"] = "true"

  # Keep sibling packages and retained legacy inputs out of this gem's archive.
  candidate_files    = Dir.glob(%W[README* LICENSE* lib/html_to_markdown.rb lib/html_to_markdown/**/* ext/html_to_markdown_rb/**/* sig/**/* Steepfile]).select { |f| File.file?(f) }
  spec.files         = candidate_files.grep_v(%r{/(?:target|tmp)/|\.(?:bundle|so|dylib|dll|o|a|log)\z|\.dSYM/})
  spec.require_paths = ["lib"]
  spec.extensions    = ["ext/html_to_markdown_rb/native/extconf.rb"]

  spec.add_dependency "rb_sys", ">= 0.9.130", "< 0.10"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
