<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:45ba1656e08d110d8ac865958ccdbbb46d0c7024150000f334eefcc0a4ca47e9
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace HtmlToMarkdown;

/**
 * Shareable, thread-safe handle to a user-provided HTML visitor implementation.
 *
 * Pass an instance wrapped in this handle to `ConversionOptions` to
 * customise how the HTML document is traversed and converted to Markdown.
 * The handle may be cloned and shared across threads without additional
 * synchronisation on the caller's side.
 */
final class VisitorHandle {}
