// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:edbe2aab8d627dd25c9d3f7fd91efffd031d7002507e913b3b81f86507b3233d
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Input exceeds the configured byte limit.
/// </summary>
public class InputTooLargeException : ConversionErrorException
{
    public InputTooLargeException(string message) : base(message) { }

    public InputTooLargeException(string message, Exception innerException) : base(message, innerException) { }
}
