# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:064efc0808295f76610289eec72587976bb57b46012598d582d50f442e420749
# To regenerate: alef generate
# To verify freshness: alef verify
"""Exception hierarchy (re-exported from the native module)."""

from ._html_to_markdown import (
    ConfigError,
    ConversionError,
    InputTooLargeError,
    InvalidInputError,
    IoError,
    OtherError,
    PanicError,
    ParseError,
    SanitizationError,
)

__all__ = [
    "ConfigError",
    "ConversionError",
    "InputTooLargeError",
    "InvalidInputError",
    "IoError",
    "OtherError",
    "PanicError",
    "ParseError",
    "SanitizationError",
]

# Re-point each exception's __module__ at the public package so tracebacks show the
# public name (e.g. "DownloadError"), not the native module name (GitHub issue #147).
_public_module = __name__.rsplit(".", 1)[0]
for _name in __all__:
    globals()[_name].__module__ = _public_module
del _name, _public_module
